FROM docker.io/bitnami/kafka:3.1.0-debian-10-r31
COPY config/. /opt/bitnami/kafka/config/
RUN ls /opt/bitnami/kafka/config/
RUN cat /opt/bitnami/kafka/config/connect-distributed.properties
RUN mkdir /opt/bitnami/kafka/libs/plugins
COPY plugins/. /opt/bitnami/kafka/libs/plugins/
RUN ls /opt/bitnami/kafka/libs/
RUN ls /opt/bitnami/kafka/libs/plugins/
CMD /opt/bitnami/kafka/bin/connect-distributed.sh /opt/bitnami/kafka/config/connect-distributed.properties