apiVersion: v1
kind: Service
metadata:
  name: yuweichou-kafka-client
spec:
  type: NodePort
  ports:
    - port: 8083
      nodePort: 32515
      protocol: TCP
      targetPort: 8083
  selector:
    run: yuweichou-kafka-client
