FROM postgres:12
COPY postgresql.conf /etc/postgresql/
ENTRYPOINT docker-entrypoint.sh -c 'shared_buffers=256MB' -c 'max_connections=200' 
CMD postgres -c 'config_file=/etc/postgresql/postgresql.conf'
